#########################
## Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50

# File Options
files:
  include:
    - "*.s+(a|c)ss"
  ignore:
    - "node_modules/**/*.s+(a|c)ss"

# Rule Configuration
rules:
  extends-before-declarations: 2
  nesting-depth:
    - 1
    - max-depth: 3
  no-color-keywords: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-important: 2
  no-invalid-hex: 2
  indentation:
    - 2
    -
      size: 2
  space-before-brace:
    - 2
    - include: true
  space-before-colon: 2
  trailing-semicolon: 2
  url-quotes: 2
  zero-unit: 2
